---
- hosts: k3s_cluster
  run_once: true
  gather_facts: yes
  become: yes
  tasks:
    - pause:
        seconds: 1
        prompt: |
          ------------------------------------------------------------------------------------------------------------------------------------
          Usage:
          ansible-playbook support/create-local-storage.yml --limit <kubernetes-node> -e local_volume_size=<size>  -e local_volume_name="vol_<size>_<count>"
          Examples:
          ansible-playbook support/create-local-storage.yml --limit node[0] -e local_volume_size=2G -e local_volume_name="vol_2_0"

          The size argument may be followed by the multiplicative suffixes KiB (=1024), MiB (=1024*1024), and so on for GiB, TiB, PiB, EiB, ZiB and YiB (the "iB" is optional,  e.g.,  "K"  has  the
          same meaning as "KiB") or the suffixes KB (=1000), MB (=1000*1000), and so on for GB, TB, PB, EB, ZB and YB.
          ------------------------------------------------------------------------------------------------------------------------------------
      changed_when: True
      when: local_volume_size is not defined or local_volume_name is not defined
    - name: "Check params are configured"
      assert:
        fail_msg: "local_volume_size and local_volume_name are required"
        that:
          - local_volume_size is defined and local_volume_name is defined

- hosts: node
  become: yes
  gather_facts: yes
  roles:
    - role: local_volume

