---

- hosts: localhost
  vars:
    ansible_connection: local
  roles:
    - k3s_facts
  tags: always


- hosts: localhost
  tasks:
    - name: "Create monitoring namespace"
      k8s:
        state: present
        definition:
          api_version: v1
          kind: Namespace
          metadata:
            name: "monitoring"

    - name: "Create default deny network policy"
      k8s:
        state: present
        definition:
          kind: NetworkPolicy
          apiVersion: networking.k8s.io/v1
          metadata:
            name: "default-deny-all"
            namespace: "monitoring"
          spec:
            podSelector: { }
            policyTypes:
              - Ingress
              - Egress
  tags: always


- hosts: localhost
  vars:
    ansible_connection: local
  roles:
    - metrics_exporter
    - monitoring
  tags: monitoring


- hosts: localhost
  vars:
    ansible_connection: local
  roles:
    - logging
  tags: logging


- hosts: localhost
  vars:
    ansible_connection: local
  roles:
    - grafana
  tags: grafana