{
 "title": "pfSense Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(system_uptime,host)"
    }
   },
   {
    "name": "wan_interface",
    "label": "wan interface",
    "query": {
     "query": "label_values(interface_status, name)"
    }
   },
   {
    "name": "opt_interface",
    "label": "opt interfaces",
    "query": {
     "query": "label_values(interface_status, name)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(interface_status, friendlyname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WAN (IPv6)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateways_defaultgw{host=\"$host\", gateway_name=\"WAN_DHCP6\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cpu_usage_idle{host=\"$host\", cpu!=\"cpu-total\"}) / 2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process information",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "processes_running{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processes_idle{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processes_sleeping{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processes_wait{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processes_blocked{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processes_zombies{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "system_load15{host=\"$host\"}",
     "legendFormat": "load15"
    },
    {
     "expr": "system_load1{host=\"$host\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "title": "WAN (IPv4)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gateways_defaultgw{host=\"$host\", gateway_name=\"WAN_PPPOE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_users{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process information",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "pf_entries{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pf_match{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pf_state_mismatch{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pf_state_insert{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\", cpu=\"cpu-total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\", cpu!=\"cpu-total\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature_degrees{host=\"$host\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used{host=\"$host\"}/ mem_total{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "mem_used{host=\"$host\"}/ mem_total{host=\"$host\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "swap_used{host=\"$host\"}/ swap_total{host=\"$host\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "disk_used{host=\"$host\",fstype!=\"nullfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Internal interfaces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "label_join(label_join(interface_status{host=\"$host\", name=~\"$opt_interface\"}, 'ip4','/','ip4_address','ip4_subnet'),'ip6','/','ip6_address','ip6_subnet')",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "gateways_delay{host=\"$host\"}",
     "legendFormat": "{{gateway_name}}"
    }
   ]
  },
  {
   "title": "Gateway loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gateways_loss{host=\"$host\"}",
     "legendFormat": "{{gateway_name}}"
    }
   ]
  },
  {
   "title": "External interfaces",
   "type": "table",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "label_join(label_join(interface_status{host=\"$host\", name=\"$wan_interface\"}, 'ip4','/','ip4_address','ip4_subnet'),'ip6','/','ip6_address','ip6_subnet')",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "gateways_defaultgw{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$interfaces traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "repeat": "interfaces",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n   0 * interface_status{host=\"$host\", friendlyname=\"$interfaces\"}, \"interface\", \"$1\", \"name\", \"(.*)\"\n) + on(interface) group_left(name) (rate(net_bytes_recv[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "label_replace(\n   0 * interface_status{host=\"$host\", friendlyname=\"$interfaces\"}, \"interface\", \"$1\", \"name\", \"(.*)\"\n) + on(interface) group_left(name) (-1 * rate(net_bytes_sent[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "$interfaces errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "repeat": "interfaces",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(\n   0 * interface_status{host=\"$host\", friendlyname=\"$interfaces\"}, \"interface\", \"$1\", \"name\", \"(.*)\"\n) + on(interface) group_left(name) (increase(net_err_in[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "label_replace(\n   0 * interface_status{host=\"$host\", friendlyname=\"$interfaces\"}, \"interface\", \"$1\", \"name\", \"(.*)\"\n) + on(interface) group_left(name) (-1 * increase(net_err_out[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-1*rate(diskio_read_bytes{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "read - {{name}}"
    },
    {
     "expr": "rate(diskio_write_bytes{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "written - {{name}}"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(diskio_io_time{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}