{
 "title": "Proxmox Overview",
 "description": "Proxmox Virtual Environment Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(pve_node_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_scaling_frequency_hertz{instance=\"$instance\"}) by (cpu)) / 2"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "VMs running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_guest_info{instance=\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "load15"
    },
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "title": "Proxmox version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_version_info{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} + 1024*1024*1024"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "VMs stopped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pve_guest_info{instance=\"$instance\"} == 0) or vector(0)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",instance=\"$instance\"}[$__rate_interval])) by (cpu)",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{instance=\"$instance\"}) + on (chip, sensor) group_left(label) (0 * node_hwmon_sensor_label{instance=\"$instance\", label!~\"tc.*\"})",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "Memory"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(node_hwmon_temp_celsius{instance=\"$instance\"}) + on (chip, sensor) group_left(label) (0 * node_hwmon_sensor_label{instance=\"$instance\", label=~\"tc.*\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "PVE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Host CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/.+\"} / pve_disk_size_bytes * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{instance=\"$instance\",template!=\"1\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=\"$instance\",template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\",template!=\"1\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=\"$instance\",template!=\"1\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info)"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{instance=\"$instance\", id=~\"storage/.+\"} * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"} * on (id, instance) group_left(name, type) pve_guest_info",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} recv"
    },
    {
     "expr": "-1*(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{instance=\"$instance\"}[$__rate_interval]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} written"
    },
    {
     "expr": "-1*((rate(pve_disk_read_bytes{instance=\"$instance\"}[$__rate_interval]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} read"
    }
   ]
  }
 ]
}