{
 "title": "TrueNAS Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(truenas_uptime, server)"
    }
   },
   {
    "name": "network_interface",
    "label": "network interface",
    "query": {
     "query": "label_values(truenas_network_if_packets_rx, interface)"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(truenas_cpu_idle, core)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(truenas_disk_ops_read, device)"
    }
   },
   {
    "name": "mount",
    "query": {
     "query": "label_values(truenas_df_complex_free, filesystem)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(truenas_cpu_system{server=\"$server\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.uptime.uptime"
    }
   ]
  },
  {
   "title": "Load 1min",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_load_shortterm{server=\"$server\"}",
     "legendFormat": "__auto",
     "target": "aliasByNode(servers.$server.load.load.shortterm,1,3)"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "truenas_load_longterm{server=\"$server\"}",
     "legendFormat": "load15"
    },
    {
     "expr": "truenas_load_shortterm{server=\"$server\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truenas_uptime{server=\"$server\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "servers.$server.uptime.uptime"
    }
   ]
  },
  {
   "title": "ZFS ARC Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "truenas_zfs2_arcstat_ratio_arc_hits{server=\"$server\"}",
     "legendFormat": "$server",
     "target": "aliasByNode(servers.$server.zfs_arc_v2.arcstat_ratio_arc-hits, 1)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU system usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "truenas_cpu_system{server=\"$server\", core=~\"$cpu\"}",
     "legendFormat": "core {{core}}"
    },
    { "legendFormat": "core {{core}}" }
   ]
  },
  {
   "title": "CPU user usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "truenas_cpu_user{server=\"$server\", core=~\"$cpu\"}",
     "legendFormat": "core {{core}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(truenas_memory_wired{server=\"$server\"} - truenas_memory_free) / truenas_memory_wired",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "truenas_swap_used{server=\"$server\"} / (truenas_swap_used+truenas_swap_free)",
     "legendFormat": "usage"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Network errors rx/tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "truenas_network_if_errors_tx{server=\"$server\", interface=~\"$network_interface\"}",
     "legendFormat": "{{interface}} - tx"
    },
    {
     "expr": "-1*truenas_network_if_errors_rx{server=\"$server\", interface=~\"$network_interface\"}",
     "legendFormat": "{{interface}} - rx"
    }
   ]
  },
  {
   "title": "Network data rx/tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "truenas_network_if_octets_tx{server=\"$server\", interface=~\"$network_interface\"}",
     "legendFormat": "{{interface}} - tx"
    },
    {
     "expr": "-1*truenas_network_if_octets_rx{server=\"$server\", interface=~\"$network_interface\"}",
     "legendFormat": "{{interface}} - rx"
    }
   ]
  },
  { "title": "Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk percent busy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "truenas_geom_busy_percent{server=\"$server\", device=~\"$disk\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "truenas_disk_temperature{server=\"$server\", device=~\"$disk\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk octets read/write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "truenas_disk_octets_write{server=\"$server\", device=~\"$disk\"}",
     "legendFormat": "{{device}} - write"
    },
    {
     "expr": "-1*truenas_disk_octets_read{server=\"$server\", device=~\"$disk\"}",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "Disk ops read/write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "truenas_disk_ops_write{server=\"$server\", device=~\"$disk\"}",
     "legendFormat": "{{device}} - write"
    },
    {
     "expr": "-1*truenas_disk_ops_read{server=\"$server\", device=~\"$disk\"}",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  { "title": "Datasets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Volume usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "truenas_df_complex_used{server=\"$server\", filesystem=~\"$mount\"} > 1000000",
     "legendFormat": "{{filesystem}}"
    }
   ]
  },
  {
   "title": "Volume usage (in %)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "truenas_df_complex_used{server=\"$server\", filesystem=~\"$mount\"} / (truenas_df_complex_used + truenas_df_complex_free) > 0.01",
     "legendFormat": "{{filesystem}}"
    }
   ]
  }
 ]
}