---

- name: "Create egress network policy for dns"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: lidarr-dns-out
        namespace: apps
        labels:
          app: lidarr
          context: dns
      spec:
        podSelector:
          matchLabels:
            app: lidarr
        egress:
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
            ports:
              - protocol: TCP
                port: 53
              - protocol: UDP
                port: 53

- name: "Create egress network policy for internet"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: lidarr-internet-out
        namespace: apps
        labels:
          app: lidarr
          context: internet
      spec:
        podSelector:
          matchLabels:
            app: lidarr
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                    - 10.0.0.0/8
                    - 192.168.0.0/16
                    - 172.16.0.0/20

- name: "Create egress network policy for transmission"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: lidarr-transmission-out
        namespace: apps
        labels:
          app: lidarr
          context: transmission
      spec:
        podSelector:
          matchLabels:
            app: lidarr
        egress:
          - to:
              - ipBlock:
                  cidr: "{{ transmission_ip }}/32"
            ports:
              - name: api
                port: 9091

- name: "Create ingress network policy for scraping"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: lidarr-scrape-in
        namespace: apps
        labels:
          app: prometheus
          context: scraping
      spec:
        podSelector:
          matchLabels:
            app: lidarr
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: monitoring
                podSelector:
                  matchLabels:
                    prometheus: monitoring
            ports:
              - protocol: TCP
                port: 9793


- name: "Create egress network policy to prowlarr"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: lidarr-prowlarr-out
        namespace: apps
        labels:
          app: lidarr
          context: prowlarr
      spec:
        podSelector:
          matchLabels:
            app: lidarr
        egress:
          - to:
              - podSelector:
                  matchLabels:
                    app: prowlarr
            ports:
              - protocol: TCP
                port: 9696


- name: "Create ingress network policy for prowlarr"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: prowlarr-lidarr-in
        namespace: apps
        labels:
          app: prowlarr
          context: lidarr
      spec:
        podSelector:
          matchLabels:
            app: lidarr
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: prowlarr
            ports:
              - protocol: TCP
                port: 8686