---

- name: "Create prowlarr ingress"
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: prowlarr
        namespace: apps
        labels:
          app: prowlarr
          context: ingress
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
      spec:
        tls:
          - hosts: [ "{{ k3s_domain }}" ]
            secretName: traefik-ingress-tls
        rules:
          - host: "{{ k3s_domain }}"
            http:
              paths:
                - path: /prowlarr
                  pathType: Prefix
                  backend:
                    service:
                      name: prowlarr
                      port:
                        name: http

- name: "Create prowlarr ingress network policy"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: prowlarr-ingress-in
        namespace: apps
        labels:
          app: prowlarr
          context: ingress
      spec:
        podSelector:
          matchLabels:
            app: prowlarr
        ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kube-system
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: traefik
            ports:
              - protocol: TCP
                port: 9696

