---

- name: "Create readarr config"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: readarr-config
        namespace: apps
        labels:
          app: readarr
      data:
        config.xml: |-
          <Config>
            <LogLevel>info</LogLevel>
            <UrlBase>/readarr</UrlBase>
            <UpdateMechanism>Docker</UpdateMechanism>
            <BindAddress>*</BindAddress>
            <Port>8787</Port>
            <SslPort>6868</SslPort>
            <EnableSsl>False</EnableSsl>
            <LaunchBrowser>True</LaunchBrowser>
            <ApiKey>55c46df3d8574e8194e1cefa84941ce1</ApiKey>
            <AuthenticationMethod>None</AuthenticationMethod>
            <Branch>master</Branch>
            <SslCertPath></SslCertPath>
            <SslCertPassword></SslCertPassword>
            <InstanceName>readarr</InstanceName>
          </Config>

- name: "Create readarr deployment"
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: readarr
        namespace: apps
        labels:
          app: readarr
      spec:
        replicas: 1
        podManagementPolicy: OrderedReady
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: readarr
        template:
          metadata:
            labels:
              app: readarr
          spec:
            restartPolicy: Always
            serviceAccountName: default
            automountServiceAccountToken: true
            dnsPolicy: ClusterFirst
            enableServiceLinks: true
            initContainers:
              - name: init-config
                image: alpine:3.6
                securityContext:
                  runAsUser: 0
                  privileged: true
                command: ["/bin/sh", "-c"]
                args:
                  - >
                    if [ ! -f /config/config.xml ]; then
                      echo "copy initial configuration"
                      cp /config.xml /config/
                    else
                      echo "volume already initialized"
                    fi
                volumeMounts:
                  - name: readarr-storage
                    mountPath: /config
                  - name: readarr-config
                    mountPath: /config.xml
                    subPath: config.xml
            containers:
              - name: readarr
                image: "linuxserver/readarr:{{ readarr_image_tag }}"
                imagePullPolicy: IfNotPresent
                env:
                  - name: TZ
                    value: "Europe/Zurich"
                  - name: PUID
                    value: "980"
                  - name: PGID
                    value: "999" # media group
                ports:
                  - name: http
                    containerPort: 8787
                    protocol: TCP
                  - name: metrics
                    containerPort: 9793
                    protocol: TCP
                resources:
                  limits:
                    cpu: 400m
                    memory: 400Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
                livenessProbe:
                  exec:
                    command:
                      - /usr/bin/env
                      - bash
                      - -c
                      - curl --fail localhost:8787/readarr/api/v1/system/status?apiKey=`IFS=\> && while read -d
                        \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
                  failureThreshold: 5
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                readinessProbe:
                  tcpSocket:
                    port: 8787
                  initialDelaySeconds: 60
                  failureThreshold: 5
                  timeoutSeconds: 2
                  periodSeconds: 10
                volumeMounts:
                  - name: readarr-storage
                    mountPath: /config
                  - name: readarr-shows
                    mountPath: /shows
            volumes:
              - name: readarr-config
                configMap:
                  name: readarr-config
                  defaultMode: 0777
              - name: readarr-shows
                emptyDir: { }
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: readarr-storage
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1.5G
              storageClassName: local-storage
              volumeMode: Filesystem

- name: "Create readarr service"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: readarr
        namespace: apps
        labels:
          app: readarr
      spec:
        type: ClusterIP
        selector:
          app: readarr
        ports:
          - name: http
            port: 8787
            targetPort: http
            protocol: TCP
