---

- name: "Create sonarr config"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: sonarr-config
        namespace: apps
        labels:
          app: sonarr
      data:
        config.xml: |-
          <Config>
            <LogLevel>info</LogLevel>
            <EnableSsl>False</EnableSsl>
            <Port>8989</Port>
            <SslPort>9898</SslPort>
            <UrlBase>/sonarr</UrlBase>
            <BindAddress>*</BindAddress>
            <ApiKey>f953853a22954df9a4cd14d1e7f780b4</ApiKey>
            <AuthenticationMethod>None</AuthenticationMethod>
          </Config>

- name: "Create sonarr deployment"
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: sonarr
        namespace: apps
        labels:
          app: sonarr
      spec:
        replicas: 1
        podManagementPolicy: OrderedReady
        strategy:
          type: Recreate
        selector:
          matchLabels:
            app: sonarr
        template:
          metadata:
            labels:
              app: sonarr
            annotations:
              prometheus.io/port: "9793"
              prometheus.io/scrape: "true"
          spec:
            restartPolicy: Always
            serviceAccountName: default
            automountServiceAccountToken: true
            dnsPolicy: ClusterFirst
            enableServiceLinks: true
            initContainers:
              - name: init-config
                image: alpine:3.6
                securityContext:
                  runAsUser: 0
                  privileged: true
                command: ["/bin/sh", "-c"]
                args:
                  - >
                    if [ ! -f /config/config.xml ]; then
                      echo "copy initial configuration"
                      cp /config.xml /config/
                    else
                      echo "volume already initialized"
                    fi
                volumeMounts:
                  - name: sonarr-storage
                    mountPath: /config
                  - name: sonarr-config
                    mountPath: /config.xml
                    subPath: config.xml
            containers:
              - name: sonarr
                image: "linuxserver/sonarr:{{ sonarr_image_tag }}"
                imagePullPolicy: IfNotPresent
                env:
                  - name: TZ
                    value: "Europe/Zurich"
                  - name: PUID
                    value: "980"
                  - name: PGID
                    value: "999" # media group
                ports:
                  - name: http
                    containerPort: 8989
                    protocol: TCP
                  - name: metrics
                    containerPort: 9793
                    protocol: TCP
                resources:
                  limits:
                    cpu: 400m
                    memory: 400Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
                livenessProbe:
                  exec:
                    command:
                      - /usr/bin/env
                      - bash
                      - -c
                      - curl --fail localhost:8989/sonarr/api/v3/system/status?apiKey=`IFS=\> && while read -d
                        \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
                  failureThreshold: 5
                  initialDelaySeconds: 60
                  periodSeconds: 10
                  successThreshold: 1
                  timeoutSeconds: 10
                readinessProbe:
                  tcpSocket:
                    port: 8989
                  initialDelaySeconds: 60
                  failureThreshold: 5
                  timeoutSeconds: 2
                  periodSeconds: 10
                volumeMounts:
                  - name: sonarr-storage
                    mountPath: /config
                  - name: sonarr-shows
                    mountPath: /shows
              - name: exporter
                image: ghcr.io/onedr0p/exportarr:v1.1.0
                imagePullPolicy: IfNotPresent
                args:
                  - sonarr
                env:
                  - name: URL
                    value: http://localhost:8989/sonarr
                  - name: APIKEY
                    value: "f953853a22954df9a4cd14d1e7f780b4"
                  - name: PORT
                    value: "9793"
                  - name: ENABLE_ADDITIONAL_METRICS
                    value: "false"
                  - name: ENABLE_UNKNOWN_QUEUE_ITEMS
                    value: "false"
                  - name: LOG_LEVEL
                    value: "WARN"
                ports:
                  - containerPort: 9793
                    name: metrics
                readinessProbe:
                  tcpSocket:
                    port: 9793
                  initialDelaySeconds: 60
                  failureThreshold: 5
                  timeoutSeconds: 2
                  periodSeconds: 10
            volumes:
              - name: sonarr-config
                configMap:
                  name: sonarr-config
                  defaultMode: 0777
              - name: sonarr-shows
                emptyDir: { }
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: sonarr-storage
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1.5G
              storageClassName: local-storage
              volumeMode: Filesystem

- name: "Create sonarr service"
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: sonarr
        namespace: apps
        labels:
          app: sonarr
      spec:
        type: ClusterIP
        selector:
          app: sonarr
        ports:
          - name: http
            port: 8989
            targetPort: http
            protocol: TCP
