{
 "title": "Container Detail",
 "description": "Detail of containers of a pod",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",pod=\"$pod\",container!=\"\"}, container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created by",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=\"$pod\",namespace=~\"$namespace\"}",
     "legendFormat": "{{ created_by_kind }}: {{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=\"$pod\", unit=\"core\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=\"$pod\", unit=\"byte\"}) by (container)"
    }
   ]
  },
  {
   "title": "Pod IP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ pod_ip }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\"}"
    }
   ]
  },
  {
   "title": "CPU throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=\"$pod\",namespace=~\"$namespace\",container=\"\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "memory saturation (100%=OOM killed!)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\",pod=\"$pod\",image!=\"\"} / container_spec_memory_limit_bytes{namespace=~\"$namespace\",pod=\"$pod\",image!=\"\"} < +Inf",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{pod=~\"$pod\",}[2m]))by(pod)",
     "legendFormat": "{{pod}}: transmit"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{pod=~\"$pod\"}[2m]))by(pod)",
     "legendFormat": "{{pod}}: receive"
    }
   ]
  },
  {
   "title": "network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$pod\",}[2m]))by(pod)",
     "legendFormat": "{{pod}}: transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$pod\"}[2m]))by(pod)",
     "legendFormat": "{{pod}}: receive"
    }
   ]
  },
  { "title": "Container $container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "container" },
  {
   "title": "Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_file_descriptors{namespace=~\"$namespace\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "core used per second\n1 = 1core/sec used per average during interval",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\",container=\"$container\"}[$__rate_interval])",
     "legendFormat": "user"
    },
    {
     "expr": "rate(container_cpu_system_seconds_total{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\",container=\"$container\"}[$__rate_interval])",
     "legendFormat": "system"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\",container=\"$container\"}[$__rate_interval])",
     "legendFormat": "combined"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=\"$pod\",namespace=~\"$namespace\",container=\"$container\",resource=\"cpu\",unit=\"core\"}",
     "legendFormat": "limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=\"$pod\",namespace=~\"$namespace\",container=\"$container\",resource=\"cpu\",unit=\"core\"}",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\",container=\"$container\"}",
     "legendFormat": "used"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=\"$pod\",namespace=~\"$namespace\",container=\"$container\",resource=\"memory\",unit=\"byte\"}",
     "legendFormat": "requested"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=\"$pod\",namespace=~\"$namespace\",container=\"$container\",resource=\"memory\",unit=\"byte\"}",
     "legendFormat": "limit"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\",container=\"$container\"}",
     "legendFormat": "workingset"
    },
    {
     "expr": "container_memory_cache{pod=\"$pod\",namespace=~\"$namespace\",image!=\"\",container=\"$container\"}",
     "legendFormat": "fscache"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_sockets{namespace=~\"$namespace\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "container_threads{namespace=~\"$namespace\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "fs used",
   "type": "timeseries",
   "description": "Number of bytes that are consumed by the container on this filesystem.\nNumber of bytes that can be consumed by the container on this filesystem.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{container=\"$container\"})by(device)",
     "legendFormat": "{{device}} usage"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{pod=~\"$pod\",container=\"$container\"}[2m]))by(pod)",
     "legendFormat": "{{pod}}: transmit"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{pod=~\"$pod\",container=\"$container\"}[2m]))by(pod)",
     "legendFormat": "{{pod}}: receive"
    }
   ]
  }
 ]
}