{
 "title": "Container Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "k8s_pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{namespace=~\"$namespace\",name!~\"POD\",image!=\"\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "memory used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\",name!~\"POD\",image!=\"\",pod=~\"$k8s_pod\"}) by (pod)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "memory saturation (100%=OOM killed!)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\",container!=\"\",pod=~\"$k8s_pod\"} / label_join(container_spec_memory_limit_bytes,\n    \"container\", \"\", \"container\") < +Inf",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU sum by container type",
   "type": "timeseries",
   "description": "core used per second\n1 = 1core/sec used per average during interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$k8s_pod\"}[$__rate_interval])) by (container,pod) ",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU throttled by container type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$k8s_pod\"}[$__rate_interval])) by (container,pod)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "core used per second\n1 = 1core/sec used per average during interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$k8s_pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU throttled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$k8s_pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "fs bytes written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\",pod=~\"$k8s_pod\"}[$__rate_interval])) by (pod, container)",
     "legendFormat": "{{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "fs bytes read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\",pod=~\"$k8s_pod\"}[$__rate_interval])) by (name,device)"
    }
   ]
  },
  {
   "title": "bytes transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$k8s_pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "bytes received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$k8s_pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}