{
 "title": "Persistent Volume Claims Overview",
 "description": "Monitors all persistent volumes that exists within a Kubernetes cluster.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "k8s_namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PVCs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 1 Week - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} )) >= (${warning_threshold} / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "Usage statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " max(label_join(kube_persistentvolumeclaim_info{namespace=~\"${k8s_namespace}\"}, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (persistentvolumeclaim,namespace,ns_pvc,storageclass,volumename)"
    },
    {
     "expr": "max(label_join(kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (ns_pvc)"
    },
    {
     "expr": "max(label_join(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (ns_pvc)"
    },
    {
     "expr": "max(label_join(kubelet_volume_stats_available_bytes{namespace=~\"${k8s_namespace}\"}/1024/1024/1024, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (pns_pvc)"
    },
    {
     "expr": "max(label_join(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Pending|Lost)\"}, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (ns_pvc) + max(label_join(kube_persistentvolumeclaim_status_phase{namespace=~\"${k8s_namespace}\",phase=~\"(Lost)\"}, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (ns_pvc)"
    },
    {
     "expr": "max(label_join(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"${k8s_namespace}\"} * 100, \"ns_pvc\", \"/\", \"namespace\", \"persistentvolumeclaim\")) by (ns_pvc)"
    }
   ]
  },
  {
   "title": "Storage Class",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "kube_storageclass_info" }
   ]
  },
  {
   "title": "Graphical usage data ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim, namespace) (kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Usage Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hourly Volume Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1h])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Usage Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{namespace=~\"${k8s_namespace}\"}[1w])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}