---

- import_tasks: prometheus_operator.yml

- import_tasks: alertmanager.yml

- import_tasks: alertmanager_ingress.yml

- import_tasks: alertmanager_network.yml

- import_tasks: prometheus.yml

- import_tasks: prometheus_ingress.yml

- import_tasks: prometheus_network.yml