---

- name: "Create ingress network policy for grafana"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: loki-grafana-in
        namespace: monitoring
        labels:
          app: grafana
          context: loki
      spec:
        podSelector:
          matchLabels:
            app: loki
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: grafana
            ports:
              - protocol: TCP
                port: 3100
              - protocol: TCP
                port: 9095

- name: "Create ingress network policy for scraping"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: loki-scrape-in
        namespace: monitoring
        labels:
          app: prometheus
          context: scraping
      spec:
        podSelector:
          matchLabels:
            app: loki
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    prometheus: monitoring
            ports:
              - protocol: TCP
                port: 3100

- name: "Create ingress network policy for promtail"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: promtail-loki-in
        namespace: monitoring
        labels:
          app: promtail
          context: loki
      spec:
        podSelector:
          matchLabels:
            app: loki
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: promtail
            ports:
              - protocol: TCP
                port: 3100

- name: "Create ingress network policy for syslog forwarder pfsense"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: syslog-forwarder-promtail-loki-in
        namespace: monitoring
        labels:
          app: syslog-forwarder
          comp: promtail
          context: loki
      spec:
        podSelector:
          matchLabels:
            app: loki
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    app: syslog-forwarder
                    comp: promtail
            ports:
              - protocol: TCP
                port: 3100