---

- name: "Create egress network policy for dns"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: promtail-dns-out
        namespace: monitoring
        labels:
          app: promtail
          context: dns
      spec:
        podSelector:
          matchLabels:
            app: promtail
        egress:
          - to:
              - namespaceSelector:
                  matchLabels:
                    kubernetes.io/metadata.name: kube-system
            ports:
              - protocol: TCP
                port: 53
              - protocol: UDP
                port: 53

- name: "Create ingress network policy for scraping"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: promtail-scrape-in
        namespace: monitoring
        labels:
          app: prometheus
          context: scraping
      spec:
        podSelector:
          matchLabels:
            app: promtail
        ingress:
          - from:
              - podSelector:
                  matchLabels:
                    prometheus: monitoring
            ports:
              - protocol: TCP
                port: 3101

- name: "Create egress network policy for loki"
  k8s:
    state: present
    definition:
      kind: NetworkPolicy
      apiVersion: networking.k8s.io/v1
      metadata:
        name: promtail-loki-out
        namespace: monitoring
        labels:
          app: promtail
          context: loki
      spec:
        podSelector:
          matchLabels:
            app: promtail
        egress:
          - to:
              - podSelector:
                  matchLabels:
                    app: loki
            ports:
              - protocol: TCP
                port: 3100